namespace TaskrowSharp.Models.IndexDataModels;

public class IndexDataPermissions
{
    public bool ViewAllClients { get; set; }
    public bool CreateClient { get; set; }
    public bool ViewAllGroups { get; set; }
    public bool ADMCompanyTeam { get; set; }
    public bool ApproveTimesheet { get; set; }
    public bool ViewEvents { get; set; }
    public bool HoursAndUtilizationRateReports { get; set; }
    public bool ADMSupplierOrder { get; set; }
    public bool ADMAdBudget { get; set; }
    public bool ADMCompanySettings { get; set; }
    public bool ADMRevenueAndPayment { get; set; }
    public bool ADMCompanyManagementReports { get; set; }
    public bool ViewPanelReport { get; set; }
    public bool ADMCompanyManagement { get; set; }
    public bool Allocation { get; set; }
    public bool Extranet { get; set; }
    public bool Intranet { get; set; }
    public bool LooseJobEntries { get; set; }
    public bool ViewAllocation { get; set; }
    public bool ViewApprovedTimesheet { get; set; }
    public bool OwnEntitiesAutoApproved { get; set; }
    public bool ControlThirdUsersTimesheet { get; set; }
    public bool ViewOrganizationChart { get; set; }
    public bool ViewOrganizationChartFunctions { get; set; }
    public bool TeamAndVacationManagement { get; set; }
    public bool Cardview { get; set; }
    public bool ADMCompanyContractsPanel { get; set; }
    public bool ADMCompanyReports { get; set; }
    public bool ViewUsers { get; set; }
    public bool ManageUsers { get; set; }
    public bool Headcount { get; set; }
    public bool EstimateTemplates { get; set; }
    public bool CreateContacts { get; set; }
    public bool CreateJobs { get; set; }
    public bool ViewJobs { get; set; }
    public bool ManagementClient { get; set; }
    public bool ClientReports { get; set; }
    public bool ViewClientAttachments { get; set; }
    public bool ApproveEstimate { get; set; }
    public bool OpportunitiesEstimatesAndProposals { get; set; }
    public bool CreateTasks { get; set; }
    public bool ViewTasks { get; set; }
    public bool ManagementJob { get; set; }
    public bool ApproveJobs { get; set; }
    public bool ApproveExpenses { get; set; }
    public bool ViewHoursAndExpensesReport { get; set; }
    public bool InsertExpenses { get; set; }
    public bool ForwardTask { get; set; }
    public bool ViewJobAttachments { get; set; }
    public bool ChangeBudgetParameters { get; set; }
    public bool ApproveBudgets { get; set; }
    public bool CloseThirdPartTasks { get; set; }
    public bool ChangeThirdPartyRequestType { get; set; }
    public bool EditTaskImNotOwner { get; set; }
    public bool CreateSubtasks { get; set; }
    public bool CreateTasksForAllGroups { get; set; }
    public bool ForwardTasksForAllGroups { get; set; }
    public bool ViewAllSubtasks { get; set; }
    public bool ForwardTasksOwnerFromAnyGroups { get; set; }
}
